Topic10_cases/Novel/novel_warehouse/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include, re_path
from django.views.static import serve

urlpatterns = [
    path('', include('apps.home.urls')),
    path('', include('apps.search.urls')),
    path('', include('apps.user.urls')),
    path('', include('apps.novel.urls')),
    path('', include('apps.feedback.urls')),
    path('', include('apps.studio.urls')),
    path('admin/', admin.site.urls),
    re_path(r'^media/(?P<path>.*)$', serve,
            {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,
            {'document_root': settings.STATIC_ROOT}),
]

handler404 = 'novel_warehouse.views.handler404'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Topic10_cases/Novel/apps/user/models.py
from django.db import models
from django.dispatch import receiver
from common.util.files import handle_file, delete_file

AVATAR_SAVE_PATH = "user/avatar/"

class User(models.Model):

    THEME_CHOICES = (
        (0, 'dark'),
        (1, 'light'),
    )

    username = models.CharField(max_length=20)
    account = models.CharField(max_length=20, unique=True)
    password = models.CharField(max_length=20)
    description = models.CharField(max_length=255, blank=True, null=True)
    avatar = models.ImageField(upload_to=AVATAR_SAVE_PATH, blank=True, null=True)
    theme = models.IntegerField(default=0, choices=THEME_CHOICES)

    def change_theme(self):
        if (self.theme == 0) :
            self.theme = 1
        else:
            self.theme = 0

    def save(self, *args, **kwargs):
        handle_file(self, "avatar", *args, **kwargs)

    def __str__(self):
        return self.account

# delete the file after the object deleted
@receiver(models.signals.post_delete, sender=User)
def auto_delete_file_on_delete(sender, instance: User, **kwargs):
    delete_file(instance.avatar)

class Subscribe(models.Model):
    reader = models.ForeignKey(User, on_delete=models.CASCADE, related_name="reader")
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="author")

    def save(self, *args, **kwargs):
        """Toggle the relation"""
        obj = Subscribe.objects.filter(reader=self.reader, author=self.author).first()
        if obj:
            obj.delete()
            return
        super(Subscribe, self).save(*args, **kwargs)

    def __str__(self):
        return f'{self.reader.username} subscribes {self.author.username}'

Topic10_cases/Novel/templates/avatar.html
{% if avatar_data.avatar %}
<img class="rounded-circle" width="{% if width %}{{ width }}{% else %}30{% endif %}px"
    height="{% if width %}{{ width }}{% else %}30{% endif %}px" src="/media/{{ avatar_data.avatar }}" alt="">
{% else %}
<svg xmlns="http://www.w3.org/2000/svg" height="25px" width="25px" fill="gray" viewBox="0 0 448 512">
    <path
        d="M224 256A128 128 0 1 0 224 0a128 128 0 1 0 0 256zm-45.7 48C79.8 304 0 383.8 0 482.3C0 498.7 13.3 512 29.7 512H418.3c16.4 0 29.7-13.3 29.7-29.7C448 383.8 368.2 304 269.7 304H178.3z" />
</svg>
{% endif %}

Topic10_cases/Novel/templates/booklist.html
{% comment %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
{% endcomment %}

<div class="book_list overflow-x-scroll d-flex">
    {% for novel in book_list %}
    <a class="btn book" style="width: 7rem; padding: 0; margin: 3px;" href="/novel/{{ novel.id }}"
        title="{{ novel.title }}" target="_blank">
        <div style="width: 7rem; height: 9.66rem;">
            <img class="w-100 h-100" src="http://{{ request.get_host }}/media/{{ novel.cover.name }}" alt="">
        </div>
        <span class="w-100  mt-2 d-inline-block textell text-truncate">{{ novel.title }}</span>
    </a>
    {% endfor %}
</div>

Topic10_cases/Novel/templates/template.html
{% load static %}

<!DOCTYPE html>
<html lang="en" data-bs-theme="{% if user %}{{ user.get_theme_display }}{% else %}dark{% endif %}">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>

    <!-- <link href="/static/styles/base.css" rel="stylesheet"> -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>

    <style>
        body {
            background-color: var(--bs-secondary-bg);
        }

        .section {
            max-width: 700px;
            background-color: var(--bs-body-bg);
            margin-bottom: 20px;
            padding-top: 1rem !important;
            padding-bottom: 1rem !important;
            padding-left: 2rem;
            padding-right: 2rem;
        }

        header .search-form {
            max-width: 500px;
            margin: 0 auto;
        }

        header .search-form input {
            text-indent: 20px;
            background-size: 15px 15px;
            background-repeat: no-repeat;
            background-position: 10px 10px;
            background-image: url('data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" height="16" width="16" fill="gray" viewBox="0 0 512 512"><path d="M416 208c0 45.9-14.9 88.3-40 122.7L502.6 457.4c12.5 12.5 12.5 32.8 0 45.3s-32.8 12.5-45.3 0L330.7 376c-34.4 25.2-76.8 40-122.7 40C93.1 416 0 322.9 0 208S93.1 0 208 0S416 93.1 416 208zM208 352a144 144 0 1 0 0-288 144 144 0 1 0 0 288z" /></svg>');
        }

        .book_list::-webkit-scrollbar {
            display: none;
        }
    </style>
    {% block style %}
    {% endblock %}
</head>

<body>
    <header>
        <div class="section container gap-3 d-flex align-items-center">
            <h2 class="m-0"><a class="navbar-brand" href="/">N</a></h2>

            <form class="flex-fill search-form" action="/search/">
                <input name="q" type="search" class="form-control shadow-none" placeholder="輸入小說名稱或作者">
            </form>

            <div class="dropdown">
                {% if user %}
                <a href="#" class="dropdown-toggle d-flex align-items-center text-decoration-none"
                    data-bs-toggle="dropdown">
                    {% include "avatar.html" with avatar_data=user %}
                </a>

                <ul class="dropdown-menu">
                    <li class="dropdown-item drop disabled d-flex align-items-center">
                        {% include "avatar.html" with avatar_data=user %}
                        <span class="ms-2">{{ user.username }}</span>
                    </li>

                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li><a class="dropdown-item" href="/profile/">個人資訊</a></li>
                    <li><a class="dropdown-item" href="/logout/">登出</a></li>

                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li><a class="dropdown-item" href="/theme/?redirect={{ request.get_full_path }}">切換主題</a></li>

                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li><a class="dropdown-item" href="/studio/work/">我的作品</a></li>
                    <li><a class="dropdown-item" href="/feed/my/">我的內容</a></li>
                    <li><a class="dropdown-item" href="/feed/bookcase/">我的書櫃</a></li>
                    <li><a class="dropdown-item" href="/feed/subscribe/">訂閱內容</a></li>
                    <li><a class="dropdown-item" href="/feed/history/">閱讀紀錄</a></li>
                </ul>
                {% else %}
                <a href="/login/" class="d-flex align-items-center text-decoration-none">
                    {% include "avatar.html" with avatar_data=user %}
                </a>
                {% endif %}
            </div>
        </div>
    </header>

    {% block content %}
    {% endblock %}
</body>

</html>